proxy-providers:
  Airport1:
    url: "http://192.168.1.185:3032/2cXaAxRGfddmGz2yx1wA/download/%E6%9C%A8%E7%93%9C%E4%BA%91"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7897  # å·²æŒ‰æ‚¨çš„è¦æ±‚ä¿®æ”¹ä¸º 7897
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
# interface-name: enp6s18
log-level: warning
find-process-mode: strict  # å·²æŒ‰æ‚¨é…ç½®ä¿®æ”¹
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# ä¸ºé˜²æ­¢ä½¿ç”¨æ’ä»¶æœ‹å‹é‡åˆ°é¢æ¿é—®é¢˜ï¼Œæˆ‘æ³¨é‡Šæ‰äº†æ­¤æ¨¡å—ã€‚
# è·‘è£¸æ ¸æœ‹å‹è‡ªè¡Œåˆ é™¤æ³¨é‡Šå³å¯ï¼Œä½¿ç”¨nikkiä»…å†…æ ¸çš„uiè·¯å¾„æ”¹ä¸º/etc/nikki/run/ui
#external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: "/etc/mihomo/ui"
#external-ui-name: zashboard
#external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - dlg.io.mi.com
    - "+.push.apple.com"

# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16  # æŒ‰æ‚¨é…ç½®
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.localdomain"
    - "+.stun.*"
    - "+.turn.*"
    - "+.webrtc.*"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
  nameserver:
    - https://223.5.5.5/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - https://119.29.29.29/dns-query

# Tunnel é…ç½®
tun:
  enable: true
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  udp-timeout: 300
  device: Mihomo  # è‹¥ä½¿ç”¨è‡ªå®šä¹‰è®¾å¤‡åå¯å–æ¶ˆæ³¨é‡Š

# è§„åˆ™åŒ¹é…
rules:
  - RULE-SET,GitHub,ğŸ“˜ GitHub
  - RULE-SET,Telegram,ğŸ™‹ Telegram
  - RULE-SET,Twitter,ğŸ•Šï¸ Twitter(X)
  - RULE-SET,Facebook,ğŸ—£ï¸ Facebook
  - RULE-SET,YouTube,ğŸï¸ YouTube
  - RULE-SET,Apple,ğŸ Apple
  - RULE-SET,Microsoft,â“‚ï¸ Microsoft
  - RULE-SET,Google,ğŸ‡¬ğŸ‡´ Google
  - OR,((RULE-SET,Steam),(RULE-SET,SteamCN)),ğŸ® Steam
  - RULE-SET,Epic,ğŸ•¹ï¸ Game (Epic)
  - RULE-SET,EA,ğŸ•¹ï¸ Game (EA)
  - OR,((RULE-SET,ChinaMaxNoIP_Domain),(RULE-SET,ChinaMaxNoIP)),â¡ï¸ å›½å†…
  - RULE-SET,Privacy,ğŸ”’ éšç§
  - RULE-SET,ChinaIPs_Classical_No_IPv6_No_Resolve,â¡ï¸ å›½å†…,no-resolve
  - OR,((RULE-SET,Global),(RULE-SET,Global_Domain)),ğŸŒ å›½å¤–
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è§„åˆ™é›†å®šä¹‰
rule-providers:
  GitHub:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  Telegram:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  Twitter:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  Facebook:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list
    type: http
    interval: 86400
    behavior: domain
    format: text
    proxy: å›½å¤–ç­–ç•¥
  Apple:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
    type: http
    interval: 86400
    behavior: domain
    format: text
    proxy: å›½å¤–ç­–ç•¥
  Microsoft:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  YouTube:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  Google:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google_No_Resolve.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  Steam:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    type: http
    interval: 86400
    behavior: domain
    format: text
    proxy: å›½å¤–ç­–ç•¥
  SteamCN:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.yaml
    type: http
    interval: 86400
    behavior: domain
    format: text
    proxy: å›½å¤–ç­–ç•¥
  Epic:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
    type: http
    interval: 86400
    behavior: domain
    format: text
    proxy: å›½å¤–ç­–ç•¥
  EA:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
    type: http
    interval: 86400
    behavior: domain
    format: text
    proxy: å›½å¤–ç­–ç•¥
  ChinaIPs_Classical_No_IPv6_No_Resolve:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs_Classical_No_IPv6_No_Resolve.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  ChinaMaxNoIP:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMaxNoIP/ChinaMaxNoIP.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  ChinaMaxNoIP_Domain:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMaxNoIP/ChinaMaxNoIP_Domain.yaml
    type: http
    interval: 86400
    behavior: domain
    format: text
    proxy: å›½å¤–ç­–ç•¥
  Global:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global_No_Resolve.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥
  Global_Domain:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global_Domain.yaml
    type: http
    interval: 86400
    behavior: domain
    format: text
    proxy: å›½å¤–ç­–ç•¥
  Privacy:
    url: https://edgeone.gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Privacy/Privacy_Classical.yaml
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    proxy: å›½å¤–ç­–ç•¥

proxy-groups:
  # å›½å†…ç­–ç•¥ç»„
  - {name: å›½å†…ç­–ç•¥, type: select, proxies: [å›½å†…è‡ªåŠ¨é€‰æ‹©, å›½å†…æ‰‹åŠ¨é€‰æ‹©, DIRECT]}
  - {name: å›½å†…è‡ªåŠ¨é€‰æ‹©, type: url-test, url: 'https://cp.cloudflare.com/generate_204', interval: 300, tolerance: 50, filter: '^(?=.*(ä¸­å›½|å¤§é™†|China|CN|cn|åŒ—äº¬|ä¸Šæµ·|å¹¿å·|æ·±åœ³|æ­å·|æˆéƒ½|é‡åº†|å¤©æ´¥|æ­¦æ±‰|è¥¿å®‰|å—äº¬|è‹å·|é’å²›|å¤§è¿|å¦é—¨|ç¦å·|é•¿æ²™|éƒ‘å·|æµå—|æ²ˆé˜³|é•¿æ˜¥|å“ˆå°”æ»¨|çŸ³å®¶åº„|å¤ªåŸ|å…°å·|é“¶å·|è¥¿å®|ä¹Œé²æœ¨é½|æ‹‰è¨|æ˜†æ˜|è´µé˜³|å—å®|æµ·å£|å—æ˜Œ|åˆè‚¥|å‘¼å’Œæµ©ç‰¹|æ²³åŒ—|å±±è¥¿|è¾½å®|å‰æ—|é»‘é¾™æ±Ÿ|æ±Ÿè‹|æµ™æ±Ÿ|å®‰å¾½|ç¦å»º|æ±Ÿè¥¿|å±±ä¸œ|æ²³å—|æ¹–åŒ—|æ¹–å—|å¹¿ä¸œ|å¹¿è¥¿|æµ·å—|å››å·|è´µå·|äº‘å—|è¥¿è—|é™•è¥¿|ç”˜è‚ƒ|é’æµ·|å®å¤|æ–°ç–†|å†…è’™å¤|ç§»åŠ¨|è”é€š|ç”µä¿¡|å¹¿ç”µ|BGP|è‡ªå»º))(?=.*(è½åœ°|éš§é“|ä¸­è½¬))?.*$', include-all: true}
  - {name: å›½å†…æ‰‹åŠ¨é€‰æ‹©, type: select, filter: '^(?=.*(ä¸­å›½|å¤§é™†|China|CN|cn|åŒ—äº¬|ä¸Šæµ·|å¹¿å·|æ·±åœ³|æ­å·|æˆéƒ½|é‡åº†|å¤©æ´¥|æ­¦æ±‰|è¥¿å®‰|å—äº¬|è‹å·|é’å²›|å¤§è¿|å¦é—¨|ç¦å·|é•¿æ²™|éƒ‘å·|æµå—|æ²ˆé˜³|é•¿æ˜¥|å“ˆå°”æ»¨|çŸ³å®¶åº„|å¤ªåŸ|å…°å·|é“¶å·|è¥¿å®|ä¹Œé²æœ¨é½|æ‹‰è¨|æ˜†æ˜|è´µé˜³|å—å®|æµ·å£|å—æ˜Œ|åˆè‚¥|å‘¼å’Œæµ©ç‰¹|æ²³åŒ—|å±±è¥¿|è¾½å®|å‰æ—|é»‘é¾™æ±Ÿ|æ±Ÿè‹|æµ™æ±Ÿ|å®‰å¾½|ç¦å»º|æ±Ÿè¥¿|å±±ä¸œ|æ²³å—|æ¹–åŒ—|æ¹–å—|å¹¿ä¸œ|å¹¿è¥¿|æµ·å—|å››å·|è´µå·|äº‘å—|è¥¿è—|é™•è¥¿|ç”˜è‚ƒ|é’æµ·|å®å¤|æ–°ç–†|å†…è’™å¤|ç§»åŠ¨|è”é€š|ç”µä¿¡|å¹¿ç”µ|BGP|è‡ªå»º))(?=.*(è½åœ°|éš§é“|ä¸­è½¬))?.*$', include-all: true}

  # å›½å¤–ç­–ç•¥ç»„
  - {name: å›½å¤–ç­–ç•¥, type: select, proxies: [å›½å¤–è‡ªåŠ¨é€‰æ‹©, å›½å¤–æ‰‹åŠ¨é€‰æ‹©, DIRECT]}
  - {name: å›½å¤–è‡ªåŠ¨é€‰æ‹©, type: url-test, url: 'https://cp.cloudflare.com/generate_204', interval: 300, tolerance: 50, filter: '^(?=.*(.))(?!.*((?i)ç¾¤|é‚€è¯·|è¿”åˆ©|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author)\b|(\d{4}-\d{2}-\d{2}))).*$', include-all: true}
  - {name: å›½å¤–æ‰‹åŠ¨é€‰æ‹©, type: select, filter: '^(?=.*(.))(?!.*((?i)ç¾¤|é‚€è¯·|è¿”åˆ©|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author)\b|(\d{4}-\d{2}-\d{2}))).*$', include-all: true}

  # åº”ç”¨ç­–ç•¥ç»„
  - {name: ğŸ“˜ GitHub, type: select, proxies: [å›½å¤–ç­–ç•¥, å›½å†…ç­–ç•¥]}
  - {name: ğŸ™‹ Telegram, type: select, proxies: [å›½å¤–ç­–ç•¥]}
  - {name: ğŸ•Šï¸ Twitter(X), type: select, proxies: [å›½å¤–ç­–ç•¥]}
  - {name: ğŸ—£ï¸ Facebook, type: select, proxies: [å›½å¤–ç­–ç•¥]}
  - {name: ğŸ Apple, type: select, proxies: [å›½å¤–ç­–ç•¥, å›½å†…ç­–ç•¥]}
  - {name: â“‚ï¸ Microsoft, type: select, proxies: [å›½å¤–ç­–ç•¥, å›½å†…ç­–ç•¥]}
  - {name: ğŸ® Steam, type: select, proxies: [å›½å¤–ç­–ç•¥, å›½å†…ç­–ç•¥]}
  - {name: ğŸ•¹ï¸ Game (Epic), type: select, proxies: [å›½å¤–ç­–ç•¥, å›½å†…ç­–ç•¥]}
  - {name: ğŸ•¹ï¸ Game (EA), type: select, proxies: [å›½å¤–ç­–ç•¥, å›½å†…ç­–ç•¥]}
  - {name: ğŸï¸ YouTube, type: select, proxies: [å›½å¤–ç­–ç•¥]}
  - {name: ğŸ‡¬ğŸ‡´ Google, type: select, proxies: [å›½å¤–ç­–ç•¥, å›½å†…ç­–ç•¥]}
  - {name: â¡ï¸ å›½å†…, type: select, proxies: [å›½å†…ç­–ç•¥]}
  - {name: ğŸŒ å›½å¤–, type: select, proxies: [å›½å¤–ç­–ç•¥]}
  - {name: ğŸ”’ éšç§, type: select, proxies: [REJECT, å›½å†…ç­–ç•¥, å›½å¤–ç­–ç•¥]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [å›½å¤–ç­–ç•¥, å›½å†…ç­–ç•¥, DIRECT]}
